### ISSUE TITLE
Line breaks on container titles fail sometimes

### ISSUE THREAD

**Issue by daguito81** [nuxxapp/nuxx#11]
It seems that when a contianer name is too long. It will break the title into a new line, but it seems like it fails for some which  ends up looking like this:
![image](https://user-images.githubusercontent.com/14969458/83494968-575e7500-a4b7-11ea-81b6-bc00488e1053.png)

I'm guessing it's the use of underscore instead of dash in the name. But not 100% sure

**Comment by daguito81** [comment]
maybe this could be fixed by allowing the box to be resized.

**Comment by corpulent** [comment]
@daguito81 thanks for the report.  I deployed a fix.  Let me know if this works.  Ill consult a UI colleague of mine on box resizing to a certain degree.

**Comment by daguito81** [comment]
Seems to be working fine now. Ill close this
![image](https://user-images.githubusercontent.com/14969458/83509141-461f6380-a4cb-11ea-902c-6275771c0507.png)
