### ISSUE TITLE
Empty environment variables create invalid compose file

### ISSUE THREAD

**Issue by xcad2k** [nuxxapp/nuxx#13]
**Description:**
If you add environment variables with blank input, it creates an invalid compose file filing "!!null '':" to the environment section. To fix this delete blank fields in "environment" tab.

**Steps to reproduce:**
1. Create a new service object
2. Edit service settings
3. Click on "environment" tab
4. Click on add with blank values
5. Close the service object

**Screenshots:**
![image](https://user-images.githubusercontent.com/28359525/83504957-719f4f80-a4c5-11ea-9837-e32c29cbae8f.png)

**Comment by corpulent** [comment]
@xcad2k Thanks for pointing this out.  I deployed a quick fix for now, but will think of a better UX for this.

**Comment by corpulent** [comment]
There is a warning now for empty environment variable keys.
