### ISSUE TITLE
Service objects with same name

### ISSUE THREAD

**Issue by xcad2k** [nuxxapp/nuxx#14]
**Description:**
When creating service objects with the same name, they're visible on the GUI but not in the compose file. Creating multiple service objects with the same name shouldn't be possible via the GUI. When adding a new object from the same image appending a "1", "2", ... suffix should be considered.

**Steps to reproduce:**
Add multiple service objects from same image

**Screenshots:**
![image](https://user-images.githubusercontent.com/28359525/83505681-67ca1c00-a4c6-11ea-8a48-e2bedd7bc55c.png)

**Comment by corpulent** [comment]
@xcad2k thanks for the report,  pushing this fix out in a few hours.

**Comment by xcad2k** [comment]
Sounds like a good solution. I would definitely add a validation to prevent objects with same name

**Comment by corpulent** [comment]
Ill keep this open for now, until we get that fix in.

**Comment by corpulent** [comment]
We implemented this fix.

<img width="765" alt="Screen Shot 2020-06-03 at 9 29 29 AM" src="https://user-images.githubusercontent.com/849403/83642414-cd78df80-a57c-11ea-8a25-76723e3197cb.png">
