### ISSUE TITLE
Feature Request: User accounts

### ISSUE THREAD

**Issue by LilTrublMakr** [nuxxapp/nuxx#16]
I would like to see user accounts for this program. I think it would benefit in a lot of ways including being able to edit setups and a couple of feature requests I have in mind. This would probably be something to do sooner rather than later so if you do decide to implement an account system, you wouldn't have to do a lot of rework coding in the future.

**Comment by xcad2k** [comment]
Would be a good idea, +1 for OAuth as well.

**Comment by corpulent** [comment]
@xcad2k what do you mean by OAuth?  Is this for some sort of integration?

**Comment by xcad2k** [comment]
OAuth can be used to easily authenticate users via other service providers, f.e. Google accounts, Facebook, etc.
There is good documentation available about that here: https://developers.google.com/identity/protocols/oauth2/web-server

It is an easy approach to offer some kind of user authentication without the need to manage and maintain user credentials. Your app will redirect user auth to the service provider API, which will handle then authentication. Once this is successful it will redirect the user back to your web-app via a callback URL.

**Comment by LilTrublMakr** [comment]
I personally do not use OAuth because if they have access to those credentials, then it is the same as using the same username/pass for every site. Plus, if they have a section that lets you see every site you use with those credentials, it makes it so much easier for whoever have access to those as well. I however, would like to see 2FA. That shouldn't be too hard to integrate.

**Comment by LilTrublMakr** [comment]
Actually that is what xcad2k is suggesting. I am completely fine with that but I would much rather use my own email/password since I use a different password for everything. I am just pointing out that if someone gets your user info for the SSO (single sign on) that xcad2k is suggesting, then that unauthorized person will have access to all accounts that uses that SSO. To me, that is not secure. The only way to mitigate it is to have 2FA (2 factor authentication) enabled.

By no means am I saying that SSO shouldn't be implemented, I am just trying to point out the security risk of it.

**Comment by corpulent** [comment]
@LilTrublMakr oh yea, that is definitely a security risk.    I am deploying some major improvements in a few hours, then will start working on the user registration part.  This will also allow users to view all of their existing projects,  the ones that where created when they where logged in of course.  And with that the global environment variables to be used across the project in this format `${DOCKERDIR}`.

**Comment by corpulent** [comment]
@xcad2k @LilTrublMakr User accounts are deployed now,  you can register/login with email/password,  or with GitHub.  I can add other authentication methods like Google, but want to give this thorough testing first.
