### ISSUE TITLE
External Image Configuration Support

### ISSUE THREAD

**Issue by rkttu** [nuxxapp/nuxx#18]
It would be better to support specifying custom images manually when adding a container. For example, in the case of Windows container, Microsoft pushes mainstream images on their own registry, not to docker hub. But despite this, docker hub syndicates image information to mcr.microsoft.com.

**Comment by corpulent** [comment]
@rkttu I added a quick way of adding a custom image and tag.  I think the next step is to integrate private repo support, which can go into its own issue.  Take a look at this.  Ill close this issue for now,  but feel free to re-open if you have suggestions for improving the current fix.
<img width="721" alt="Screen Shot 2020-07-03 at 7 09 40 AM" src="https://user-images.githubusercontent.com/849403/86463789-2b275580-bcfc-11ea-8286-bdd47ca45eb8.png">
