### ISSUE TITLE
Enhancement: Cursor change on hover

### ISSUE THREAD

**Issue by LilTrublMakr** [nuxxapp/nuxx#20]
Small and quick change:

```
.node[_ngcontent-cxv-c100]:hover {
  cursor: all-scroll;
}
```

This would change the cursor to the all scroll icon (arrows pointing in all directions) when hovering over one of the cards instead of keeping the default cursor. To me, it better represents that you can move the cards around.

**Comment by corpulent** [comment]
@LilTrublMakr this is in, and deployed.
