### ISSUE TITLE
Timeline of Opening sourcing

### ISSUE THREAD

**Issue by davidfic** [nuxxapp/nuxx#23]
What is your timeline of open sourcing this? You'd get a lot more adoption of this with it open.

**Comment by corpulent** [comment]
@davidfic I already started on prepping the code base for a proper local development setup,  documentation, unit testing.  Once this stuff is done,  I will publish the code here.  I am estimating sometime early next month.  I was planning sooner,  but bug fixes keep getting in the way ;) .

**Comment by corpulent** [comment]
@davidfic I can add you to the private repo in the mean time while I get things in order,  this way you can use it in your organization this week.  The current small user base of this tool reported so many feature requests,  bugs and improvements that it set me back a bit.

Can you share how you would need to run this tool within your organization?  I am thinking you would just run `docker-compose up` and have the whole thing working either on your local machine or a server.  I have the docker-compose.yaml setup,  but I can also create kubernetes deployment files.

**Comment by corpulent** [comment]
@davidfic @xcad2k the project is open sourced now.  Let me know what you guys thing.  Closing this issue.

**Comment by basudip** [comment]
just got the notification. you just did an amazing job for the community. I am a .net guy. don't have much exp in Angular. but will to test your build locally. 
clone the repo and run "docker-compose local_setup" right?

**Comment by corpulent** [comment]
@basudip Thanks a lot man,  did my best,  first time releasing something into open source, and honestly I am really self conscious about my code quality.

Im assuming you are running windows, just make sure you got Docker and Docker Compose installed, and just do `make local_setup`.  I suggest you get GCC make command installed, so you can run my make commands.  If not, then you will have to run them individually like this.

```
cd ./src/composer && npm install && npm run build_local

... go back to the project root

docker-compose up -d

... wait for a few seconds

docker exec -it nuxx-api python /home/app/manage.py makemigrations
docker exec -it nuxx-api python /home/app/manage.py migrate
docker exec -it nuxx-api python /home/app/manage.py collectstatic --noinput
```

I suggest you get in my Slack channel https://join.slack.com/t/nuxxapp/shared_invite/zt-fkgoyz5h-CYo5tqAT0CwRZMpuOJYAJA so you can message me directly.

**Comment by basudip** [comment]
Yes, I use windows for development but docker on windows is a big no for me. for docker usually, I use Raspberry or a VM if no other option left.
