### ISSUE TITLE
Feature Request: Networks

### ISSUE THREAD

**Issue by LilTrublMakr** [nuxxapp/nuxx#3]
I have been poking around a little bit and do not see a way to add a network to containers. I like how you have the volumes set up so I personally think something like that would work well for a network as well.

**Comment by davidfic** [comment]
It would also be great to add a new connection point so you can visually connect different containers via networks

**Comment by corpulent** [comment]
@davidfic @LilTrublMakr I deployed networks functionality.  Let me know what you guys think. User feedback really helps to improve things.  There is a good chance I might have missed something,  or the generated code is not 100% correct at least with the properties currently exposed in the UI.  If that is the case,  we can open a new issue and list it all there.

Sample project I am using to test,  it open to editing https://nuxx.io/NX82pm06jv

**Comment by corpulent** [comment]
@davidfic I will move your request to a separate issue.
