### ISSUE TITLE
Enhancement: Mobile support 

### ISSUE THREAD

**Issue by Klizzy** [nuxxapp/nuxx#5]
The application is currently not optimized for mobile. It would be nice to have a response layout, so mobile work ist possible.

**Comment by corpulent** [comment]
@Klizzy I pushed some mobile improvements for the short term, I really have to give mobile more thought.  Let me know what you think.  Also,  what mobile device are you using?

**Comment by corpulent** [comment]
Going to close this for now,  will be adding more specific mobile UI improvements issues.
