### ISSUE TITLE
Feature Request: Expose ports

### ISSUE THREAD

**Issue by pcgeek86** [nuxxapp/nuxx#6]
I poked around for a minute, and couldn't find a way to create port mappings between the host and container, or specify the `host` networking option. Please consider adding this, so I can expose ports to access applications running in containers!

**Comment by pcgeek86** [comment]
Closing. Just found it. My eyes skipped past it. Maybe a UI improvement then? :)

**Comment by corpulent** [comment]
@pcgeek86 I am going to re-open this to do some UI improvements tomorrow.  It is kind of hidden,  you are right.

**Comment by pcgeek86** [comment]
Thanks @corpulent. It just looked like a section header to me, so I accidentally missed it. Much appreciated.

**Comment by corpulent** [comment]
@pcgeek86 thanks a ton for that tweet! haha

**Comment by pcgeek86** [comment]
@corpulent Thanks a ton for the great idea and implementation! 👍

**Comment by corpulent** [comment]
![Screen Shot 2020-06-02 at 2 11 18 AM](https://user-images.githubusercontent.com/849403/83486044-59ecaa80-a476-11ea-8a16-cd0344ddd2a6.png)

@pcgeek86 I made it more readable, and compact, with default values suggested by Docker Compose docs.  Its deployed also.  Thanks for reporting this.
