### ISSUE TITLE
import existing compose file

### ISSUE THREAD

**Issue by davidfic** [nuxxapp/nuxx#7]
I already have my compose files written and I'd like to be able to import them and visualize them. Having a way to import the existing code would be great

**Comment by corpulent** [comment]
@davidfic this feature is in the pipeline.  I should push it out early next week the latest.

**Comment by xcad2k** [comment]
Great feature, looking forward to this, too!

**Comment by basudip** [comment]
I am upvoting this. one of the most needed feature.

**Comment by corpulent** [comment]
@basudip I will release this by mid to end of this week,  got a little stuck on authentication over the weekend.

**Comment by corpulent** [comment]
@davidfic @basudip @xcad2k hey guys,  I deployed the importing feature.  Here is a sample https://nuxx.io/?import_url=https:%2F%2Fraw.githubusercontent.com%2Frudderlabs%2Frudder-server%2Fmaster%2Fdocker-compose-multi.yml. It takes in a raw yaml file,  by clicking "Import" -> "Link".  If you have a few minutes,  test this out and suggest improvements if you can.  I will also be testing with different files.

**Comment by basudip** [comment]
> 
> 
> @davidfic @basudip @xcad2k hey guys, I deployed the importing feature. Here is a sample https://nuxx.io/?import_url=https:%2F%2Fraw.githubusercontent.com%2Frudderlabs%2Frudder-server%2Fmaster%2Fdocker-compose-multi.yml. It takes in a raw yaml file, by clicking "Import" -> "Link". If you have a few minutes, test this out and suggest improvements if you can. I will also be testing with different files.

Hi, really appreciate the hard work. tested a few online repositories. but if user upload there own yml from there PC or copy-paste the text directly to the editor then it will be more convenient. still testing have not found any bug yet. 
I don't know if it's only me, but the font size of the left-hand side visual designer is too small. I have to zoom in the entire page to see it. other than this it's working perfectly.

**Comment by corpulent** [comment]
@basudip the issue to paste code into the editor and edit it directly is here https://github.com/nuxxapp/nuxx/issues/22.  Hoping to push this out this week.

The font size is too small you are right.  I will adjust the default zoom, and increase the font size.

If you have other suggestions to make this tool more utility,  feel free to create issues here.  I will open source the code early next month,  so people can open PRs for improvements.

**Comment by davidfic** [comment]
I tried importing my compose file from Github and nothing was rendered to the screen. There was no indication of anything happening at all. 

I clicked the Link button, entered my [compose file](https://github.com/davidfic/VPN-media-stack/blob/master/docker-compose.yml) in the dialog and clicked import and nothing happened.

**Comment by corpulent** [comment]
@davidfic I am working on handling this better.  The issue is that the backend wants a raw yaml string like this https://raw.githubusercontent.com/davidfic/VPN-media-stack/master/docker-compose.yml

So this will work,  https://nuxx.io/?import_url=https:%2F%2Fraw.githubusercontent.com%2Fdavidfic%2FVPN-media-stack%2Fmaster%2Fdocker-compose.yml

I have a small list of tasks to run through to improve UX for importing.  Another reason to open source this project.

**Comment by davidfic** [comment]
OK the import of the raw file works. I'll test out that all the other parts work as well. I did notice that when I clicked the Volumes button that nothing was shown and I assume it's there to add volumes, but the way it is laid out it made me assume that after an import it would show all the mounted volumes. Maybe some clarity on that button

**Comment by corpulent** [comment]
@davidfic This feeback is good.  I released an update last night,  with imports through URL and as a copy and paste into the editor.  Plus improvements on the UI addressing what you describe with Volumes.  The Volumes button on the canvas is for top level volume declarations,  not for relative mount paths.

If you have a few minutes please test out the new UI improvements,  and if you can, can you describe your ideal workflow use of the tool?
